Changed assertCalledOnceWith() to assert_called_once_with()
When I change assertCalledOnceWith() to assert_called_once_with(), make test succeeds but shows another failure:
```
AssertionError: Expected call: mock(sentinel.size, sentinel.modified_time)
Actual call: mock(sentinel.since, sentinel.modified_time, sentinel.size)
```
After changing the call accordingly, all 59 tests succeed.